globals:
  onFailure:
  - handlerName: my-handler


failureHandlers:
- name: my-handler
  image: busybox
  script: |
    printenv | grep ICE  

services:
- name: www_svc
  image: nginx

steps:
- name: always-there
  containerRun:
    image: busybox
    script: |
      env 

- name: service
  serviceRun:
    name: www
    image: nginx

- name: service-check
  containerRun:
    image: busybox
    script: |
      sleep 10
      
      
      
      
