globals:
  onFailure:
  - handlerName: my-handler


failureHandlers:
- name: my-handler
  image: busybox
  script: |
    printenv | grep ICE  

services:
- name: test
  image: nginx

steps:
- name: always-there
  containerRun:
    image: busybox
    files:
    - path: /var/myfile
      fromSecret: content
    script: |
      ls /var
