steps:
- name: env-test
  when:
    branch: ["master"]
  dockerRun:
    image: busybox
    script: |
      printenv
    environment:
    - name: TESTENV
      value: testSecret
- name: filter-test
  when:
    branch: ["filter"]
  dockerRun:
    image: busybox
    script: |
      printenv
    



