steps:
- name: env-test
  dockerRun:
    image: busybox
    script: |
      printenv
    environment:
    - name: TESTENV
      value: testSecret
- name: filter-test
  dockerRun:
    image: busybox
    script: |
      printenv
- name: tag-test
  when:
    event: ["tag"]
  dockerRun:
    image: busybox
    script: |
      printenv
    



