steps:
- name: feature-wildcard
  when:
    event: ["commit"]
    branch: ["feature"]
  dockerRun:
    image: busybox
    script: |
      printenv
    environment:
    - name: TESTENV
      value: testSecret
- name: filter-test
  when:
    event: ["commit"]
    branch: ["feature"]
    skipBranch: ["feature-skip"]
  dockerRun:
    image: busybox
    script: |
      printenv
