steps:
- name: feature-wildcard
  when:
    branch: ["feature-*"]
  dockerRun:
    image: busybox
    script: |
      printenv
    environment:
    - name: TESTENV
      value: testSecret
- name: filter-test
  when:
    branch: ["feature-*"]
    skipBranch: ["feature-skip"]
  dockerRun:
    image: busybox
    script: |
      printenv
